export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';


export const TRIP_ADD_SUCCESS = 'TRIP_ADD_SUCCESS';
export const TRIP_UPDATE_SUCCESS = 'TRIP_UPDATE_SUCCESS';
export const TRIP_OUT_SUCCESS = 'TRIP_OUT_SUCCESS';
export const TRIP_BACK_SUCCESS = 'TRIP_BACK_SUCCESS';
export const LOAD_TRIPS_SUCCESS = 'LOAD_TRIPS_SUCCESS';
export const DELETE_TRIP_SUCCESS = 'DELETE_TRIP_SUCCESS';

export const USER_AUTHENTICATION_SUCCESS = 'USER_AUTHENTICATION_SUCCESS';
export const LOG_OUT = 'LOG_OUT';